### ISSUE TITLE
The generated paths in the r.js config file should be relative to the modified file

### ISSUE THREAD

**Issue by davidpelaez** [yeoman/bower-requirejs#15]
Consider Yeoman's 1.0 webapp generator. The file lives in /app/scripts/main.js

```
bower:
            options:
                exclude: ["modernizr"]
            all:
                rjsConfig: "<%= yeoman.app %>/scripts/main.js"
```

 This would modify main.js creating the paths entries but not relative to the location of main.js, as a result the auto generated main.js fails.

In the following code all app/ should be replaced by ../

```
require.config({
    "paths": {
        "bootstrap": "vendor/bootstrap",
        "jquery": "app/components/jquery/jquery",
        "angular": "app/components/angular/angular",
        "angular-cookies": "app/components/angular-cookies/angular-cookies",
        "angular-mocks": "app/components/angular-mocks/angular-mocks",
```
